import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Generate `src/data/proof.ts` by actually running the claim suite.
 *
 * Any surface that says "thirty-two claims" is making a claim of its own, and
 * this project has already been caught twice writing a count into copy that the
 * code had outgrown — "fifteen surfaces" on the page about counting surfaces,
 * "eight messages" on a thread that renders eleven. So the numbers describing
 * the proof are themselves generated from the proof, and `--check` fails the
 * build if the file has drifted from what the suite actually reports.
 *
 * It runs the real checker rather than counting `expect(` call sites in the
 * source: most of those sit inside loops, so the static count would understate
 * the truth by a factor of three and be wrong in the flattering direction.
 */

const ROOT = process.cwd();
const OUT = join(ROOT, 'src', 'data', 'proof.ts');
const CHECK_ONLY = process.argv.includes('--check');

function measure() {
  let stdout = '';
  try {
    stdout = execFileSync('npx', ['tsx', 'scripts/check-ranking.ts'], {
      cwd: ROOT,
      encoding: 'utf8',
      maxBuffer: 32 * 1024 * 1024,
      shell: process.platform === 'win32',
    });
  } catch (error) {
    // A failing suite must not silently produce a proof file claiming success.
    console.error('the claim suite did not pass; refusing to write a proof of it');
    if (error.stdout) console.error(String(error.stdout).slice(-2000));
    process.exit(1);
  }

  const passes = (stdout.match(/^\s*PASS\s/gm) ?? []).length;
  const failures = (stdout.match(/^\s*FAIL\s/gm) ?? []).length;
  const claims = new Set(
    [...stdout.matchAll(/^Claim (\d+)\b/gm)].map((m) => Number(m[1])),
  ).size;

  if (failures > 0) {
    console.error(`${failures} assertion(s) failed; refusing to write a proof file`);
    process.exit(1);
  }

  return { claims, assertions: passes };
}

function render({ claims, assertions }, routes) {
  return `// GENERATED by scripts/build-proof.mjs — do not edit.
// Run \`npm run proof\` after adding a claim. \`npm run check\` fails on drift.
//
// These three numbers describe the evidence this project offers about itself,
// which makes them the numbers most worth being pedantic about: they are read
// off a real run of the suite rather than written down beside it.

export type Proof = {
  /** Numbered claim sections in scripts/check-ranking.ts. */
  claims: number;
  /** Assertions that actually passed on the last generated run. */
  assertions: number;
  /** Surfaces in the attention inventory, including the stage. */
  routes: number;
};

export const PROOF: Proof = {
  claims: ${claims},
  assertions: ${assertions},
  routes: ${routes},
};
`;
}

const inventory = readFileSync(join(ROOT, 'src', 'data', 'attentionInventory.ts'), 'utf8');
const routes = (inventory.match(/"path":/g) ?? []).length;

const measured = measure();
const next = render(measured, routes);

if (CHECK_ONLY) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    console.error('proof is missing — run: npm run proof');
    process.exit(1);
  }
  if (current.trim() !== next.trim()) {
    console.error('proof is stale — run: npm run proof');
    process.exit(1);
  }
  console.log('proof is current');
} else {
  writeFileSync(OUT, next);
  console.log(
    `wrote src/data/proof.ts — ${measured.claims} claims, ${measured.assertions} assertions, ${routes} routes`,
  );
}
