import type { Surface } from '@/lib/attention';

/**
 * GENERATED by `scripts/measure-attention.ts`. Do not edit by hand.
 *
 * Counted from component source rather than authored, and re-measured by
 * `npm run check` so it cannot drift as the site grows. The method and its
 * limits are documented in the script.
 */
export const SURFACES: Surface[] = [
  {
    "path": "/",
    "kind": "argument",
    "words": 493,
    "decisions": 33
  },
  {
    "path": "/compiler",
    "kind": "product",
    "words": 186,
    "decisions": 8
  },
  {
    "path": "/app",
    "kind": "product",
    "words": 239,
    "decisions": 7
  },
  {
    "path": "/wednesday",
    "kind": "product",
    "words": 98,
    "decisions": 5
  },
  {
    "path": "/after",
    "kind": "product",
    "words": 171,
    "decisions": 6
  },
  {
    "path": "/next-wednesday",
    "kind": "product",
    "words": 82,
    "decisions": 4
  },
  {
    "path": "/profile",
    "kind": "product",
    "words": 229,
    "decisions": 6
  },
  {
    "path": "/held-back",
    "kind": "argument",
    "words": 258,
    "decisions": 4
  },
  {
    "path": "/double",
    "kind": "argument",
    "words": 178,
    "decisions": 4
  },
  {
    "path": "/ending",
    "kind": "argument",
    "words": 357,
    "decisions": 5
  },
  {
    "path": "/odds",
    "kind": "argument",
    "words": 131,
    "decisions": 5
  },
  {
    "path": "/network",
    "kind": "argument",
    "words": 203,
    "decisions": 3
  },
  {
    "path": "/world",
    "kind": "argument",
    "words": 129,
    "decisions": 5
  },
  {
    "path": "/mutual",
    "kind": "argument",
    "words": 347,
    "decisions": 4
  },
  {
    "path": "/thread",
    "kind": "product",
    "words": 136,
    "decisions": 7
  },
  {
    "path": "/start",
    "kind": "argument",
    "words": 145,
    "decisions": 5
  },
  {
    "path": "/film",
    "kind": "product",
    "words": 185,
    "decisions": 17
  },
  {
    "path": "/reel",
    "kind": "product",
    "words": 31,
    "decisions": 1
  },
  {
    "path": "/zoom",
    "kind": "argument",
    "words": 158,
    "decisions": 3
  },
  {
    "path": "/gravity",
    "kind": "argument",
    "words": 141,
    "decisions": 11
  },
  {
    "path": "/weather",
    "kind": "argument",
    "words": 106,
    "decisions": 5
  },
  {
    "path": "/next",
    "kind": "argument",
    "words": 229,
    "decisions": 1
  },
  {
    "path": "/attention",
    "kind": "argument",
    "words": 173,
    "decisions": 5
  },
  {
    "path": "/all",
    "kind": "argument",
    "words": 449,
    "decisions": 5
  },
  {
    "path": "/autonomy",
    "kind": "argument",
    "words": 253,
    "decisions": 6
  },
  {
    "path": "/end",
    "kind": "product",
    "words": 101,
    "decisions": 3
  },
  {
    "path": "/possibility",
    "kind": "product",
    "words": 189,
    "decisions": 7
  },
  {
    "path": "/moments",
    "kind": "product",
    "words": 51,
    "decisions": 2
  },
  {
    "path": "/vision",
    "kind": "argument",
    "words": 307,
    "decisions": 4
  }
];
