import type { Surface } from '@/lib/attention';

/**
 * GENERATED by `scripts/measure-attention.ts`. Do not edit by hand.
 *
 * Counted from component source rather than authored, and re-measured by
 * `npm run check` so it cannot drift as the site grows. The method and its
 * limits are documented in the script.
 */
export const SURFACES: Surface[] = [
  {
    "path": "/",
    "kind": "argument",
    "words": 506,
    "decisions": 29
  },
  {
    "path": "/compiler",
    "kind": "product",
    "words": 176,
    "decisions": 8
  },
  {
    "path": "/app",
    "kind": "product",
    "words": 215,
    "decisions": 7
  },
  {
    "path": "/wednesday",
    "kind": "product",
    "words": 84,
    "decisions": 5
  },
  {
    "path": "/after",
    "kind": "product",
    "words": 156,
    "decisions": 6
  },
  {
    "path": "/next-wednesday",
    "kind": "product",
    "words": 75,
    "decisions": 4
  },
  {
    "path": "/profile",
    "kind": "product",
    "words": 216,
    "decisions": 6
  },
  {
    "path": "/held-back",
    "kind": "argument",
    "words": 174,
    "decisions": 4
  },
  {
    "path": "/double",
    "kind": "argument",
    "words": 174,
    "decisions": 4
  },
  {
    "path": "/ending",
    "kind": "argument",
    "words": 296,
    "decisions": 5
  },
  {
    "path": "/odds",
    "kind": "argument",
    "words": 124,
    "decisions": 5
  },
  {
    "path": "/network",
    "kind": "argument",
    "words": 203,
    "decisions": 3
  },
  {
    "path": "/zoom",
    "kind": "argument",
    "words": 146,
    "decisions": 3
  },
  {
    "path": "/gravity",
    "kind": "argument",
    "words": 134,
    "decisions": 11
  },
  {
    "path": "/weather",
    "kind": "argument",
    "words": 106,
    "decisions": 5
  },
  {
    "path": "/next",
    "kind": "argument",
    "words": 222,
    "decisions": 1
  },
  {
    "path": "/attention",
    "kind": "argument",
    "words": 161,
    "decisions": 5
  },
  {
    "path": "/all",
    "kind": "argument",
    "words": 251,
    "decisions": 5
  },
  {
    "path": "/autonomy",
    "kind": "argument",
    "words": 248,
    "decisions": 6
  },
  {
    "path": "/end",
    "kind": "product",
    "words": 101,
    "decisions": 3
  },
  {
    "path": "/possibility",
    "kind": "product",
    "words": 180,
    "decisions": 7
  },
  {
    "path": "/moments",
    "kind": "product",
    "words": 44,
    "decisions": 2
  },
  {
    "path": "/vision",
    "kind": "argument",
    "words": 307,
    "decisions": 4
  }
];
