// GENERATED by scripts/contrast.mjs — do not edit.
// Run `npm run contrast` after changing a text colour. `npm run check` fails on drift.
//
// Every Tailwind text token in src/, composited against the surface it sits on
// and measured against WCAG AA for normal text (4.5:1). An earlier review found
// 406 failures, including the unofficial-project disclosure at 2.23:1.

export type ContrastReport = {
  /** Text-colour usages measured. */
  checked: number;
  /** Usages below 4.5:1. */
  failing: number;
};

export const CONTRAST: ContrastReport = {
  checked: 992,
  failing: 0,
};
