/**
 * GENERATED by `scripts/build-photo-manifest.mjs`. Do not edit by hand.
 * Regenerate with `npm run photos`; `npm run check` fails if this drifts
 * from the files actually in public/photos.
 */
export type Photo = {
  src: string;
  w: number;
  h: number;
  kind: 'moment' | 'room' | 'sheet';
  kb: number;
  title?: string;
};

export const PHOTOS: Photo[] = [
  {
    "src": "/photos/bookstore-reading.webp",
    "w": 1536,
    "h": 1024,
    "kind": "moment",
    "kb": 85,
    "title": "the bookstore, late"
  },
  {
    "src": "/photos/bridgeside.webp",
    "w": 1536,
    "h": 1024,
    "kind": "moment",
    "kb": 50,
    "title": "bridgeside"
  },
  {
    "src": "/photos/coffee-date.webp",
    "w": 1536,
    "h": 1024,
    "kind": "moment",
    "kb": 89,
    "title": "golden hour, two coffees"
  },
  {
    "src": "/photos/moment-01.webp",
    "w": 1122,
    "h": 1402,
    "kind": "moment",
    "kb": 80
  },
  {
    "src": "/photos/moment-02.webp",
    "w": 1122,
    "h": 1402,
    "kind": "moment",
    "kb": 79
  },
  {
    "src": "/photos/moment-03.webp",
    "w": 1122,
    "h": 1402,
    "kind": "moment",
    "kb": 65
  },
  {
    "src": "/photos/moment-04.webp",
    "w": 1536,
    "h": 1024,
    "kind": "moment",
    "kb": 89
  },
  {
    "src": "/photos/moment-05.webp",
    "w": 1122,
    "h": 1402,
    "kind": "moment",
    "kb": 116
  },
  {
    "src": "/photos/moment-06.webp",
    "w": 1122,
    "h": 1402,
    "kind": "moment",
    "kb": 117
  },
  {
    "src": "/photos/moment-07.webp",
    "w": 1122,
    "h": 1402,
    "kind": "moment",
    "kb": 105
  },
  {
    "src": "/photos/moment-08.webp",
    "w": 1122,
    "h": 1402,
    "kind": "moment",
    "kb": 117
  },
  {
    "src": "/photos/moment-09.webp",
    "w": 1122,
    "h": 1402,
    "kind": "moment",
    "kb": 101
  },
  {
    "src": "/photos/moment-10.webp",
    "w": 1536,
    "h": 1024,
    "kind": "moment",
    "kb": 59
  },
  {
    "src": "/photos/moment-11.webp",
    "w": 1536,
    "h": 1024,
    "kind": "moment",
    "kb": 80
  },
  {
    "src": "/photos/moment-12.webp",
    "w": 1448,
    "h": 1086,
    "kind": "moment",
    "kb": 74
  },
  {
    "src": "/photos/moment-13.webp",
    "w": 1122,
    "h": 1402,
    "kind": "moment",
    "kb": 101
  },
  {
    "src": "/photos/moment-14.webp",
    "w": 1122,
    "h": 1402,
    "kind": "moment",
    "kb": 43
  },
  {
    "src": "/photos/neon-downtown.webp",
    "w": 1536,
    "h": 1024,
    "kind": "moment",
    "kb": 76,
    "title": "downtown, texting nobody"
  },
  {
    "src": "/photos/neon-tacos.webp",
    "w": 1536,
    "h": 1024,
    "kind": "moment",
    "kb": 64,
    "title": "tacos by the night street"
  },
  {
    "src": "/photos/stadium-night.webp",
    "w": 1536,
    "h": 1024,
    "kind": "moment",
    "kb": 56,
    "title": "the stadium, after"
  },
  {
    "src": "/photos/study-picnic.webp",
    "w": 1536,
    "h": 1024,
    "kind": "moment",
    "kb": 80,
    "title": "the study picnic"
  },
  {
    "src": "/photos/twilight-stroll.webp",
    "w": 1448,
    "h": 1086,
    "kind": "moment",
    "kb": 59,
    "title": "campus twilight stroll"
  },
  {
    "src": "/photos/room-01.webp",
    "w": 1586,
    "h": 992,
    "kind": "room",
    "kb": 89
  },
  {
    "src": "/photos/room-02.webp",
    "w": 1586,
    "h": 992,
    "kind": "room",
    "kb": 60
  },
  {
    "src": "/photos/room-03.webp",
    "w": 1586,
    "h": 992,
    "kind": "room",
    "kb": 25
  },
  {
    "src": "/photos/room-04.webp",
    "w": 1586,
    "h": 992,
    "kind": "room",
    "kb": 93
  },
  {
    "src": "/photos/room-05.webp",
    "w": 1586,
    "h": 992,
    "kind": "room",
    "kb": 42
  },
  {
    "src": "/photos/room-06.webp",
    "w": 1586,
    "h": 992,
    "kind": "room",
    "kb": 18
  },
  {
    "src": "/photos/contact-sheet.webp",
    "w": 1536,
    "h": 1024,
    "kind": "sheet",
    "kb": 128,
    "title": "contact sheet"
  },
  {
    "src": "/photos/moodboard-2.webp",
    "w": 1536,
    "h": 1024,
    "kind": "sheet",
    "kb": 133,
    "title": "moodboard, again"
  },
  {
    "src": "/photos/moodboard.webp",
    "w": 1536,
    "h": 1024,
    "kind": "sheet",
    "kb": 133,
    "title": "moodboard"
  },
  {
    "src": "/photos/photo-grid.webp",
    "w": 1536,
    "h": 1024,
    "kind": "sheet",
    "kb": 123,
    "title": "the week in frames"
  }
];
