// GENERATED by scripts/build-proof.mjs — do not edit.
// Run `npm run proof` after adding a claim. `npm run check` fails on drift.
//
// These three numbers describe the evidence this project offers about itself,
// which makes them the numbers most worth being pedantic about: they are read
// off a real run of the suite rather than written down beside it.

export type Proof = {
  /** Numbered claim sections in scripts/check-ranking.ts. */
  claims: number;
  /** Assertions that actually passed on the last generated run. */
  assertions: number;
  /** Surfaces in the attention inventory, including the stage. */
  routes: number;
};

export const PROOF: Proof = {
  claims: 37,
  assertions: 1002,
  routes: 27,
};
